language: go
go:
    - 1.4
    - tip

install:
    - go get -v -t ./...
    - export PATH=$PATH:$HOME/gopath/bin

before_script:
    - apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
    - echo "deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen" | tee -a /etc/apt/sources.list.d/10gen.list
    - apt-get -y update
    - apt-get -y install mongodb-org-server=2.6.1
    - mkdir -p /data/db

script: go test -race
